/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerId = IDL.Nat;
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'outstandingDue' : IDL.Nat,
  'totalPurchases' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ExpenseId = IDL.Nat;
export const ExpenseCategory = IDL.Variant({
  'other' : IDL.Null,
  'labour' : IDL.Null,
  'rent' : IDL.Null,
  'transport' : IDL.Null,
  'electricity' : IDL.Null,
});
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'date' : Time,
  'description' : IDL.Text,
  'recordedBy' : IDL.Principal,
  'category' : ExpenseCategory,
  'amount' : IDL.Nat,
});
export const GSTRate = IDL.Record({
  'name' : IDL.Text,
  'percentage' : IDL.Nat,
});
export const PaymentId = IDL.Nat;
export const SaleId = IDL.Nat;
export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'bank' : IDL.Null,
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : PaymentId,
  'saleId' : SaleId,
  'date' : Time,
  'mode' : PaymentMode,
  'notes' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const ProductCategory = IDL.Variant({
  'other' : IDL.Null,
  'tile' : IDL.Null,
  'granite' : IDL.Null,
  'marble' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'minStockAlert' : IDL.Nat,
  'category' : ProductCategory,
  'currentStock' : IDL.Nat,
  'basePrice' : IDL.Nat,
  'qrCode' : IDL.Text,
});
export const SaleStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const SaleItem = IDL.Record({
  'productId' : ProductId,
  'gstAmount' : IDL.Nat,
  'quantity' : IDL.Nat,
  'gstRate' : GSTRate,
  'unitPrice' : IDL.Nat,
});
export const Sale = IDL.Record({
  'id' : SaleId,
  'paymentStatus' : SaleStatus,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'totalGST' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'invoiceNumber' : IDL.Text,
  'transportCharge' : IDL.Nat,
  'discount' : IDL.Nat,
  'customerId' : CustomerId,
  'items' : IDL.Vec(SaleItem),
  'subtotal' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Reports = IDL.Record({
  'lowStockReport' : IDL.Vec(Product),
  'expenses' : IDL.Vec(Expense),
  'totalSales' : IDL.Nat,
  'topSellingProducts' : IDL.Vec(Product),
  'totalRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func([Customer], [CustomerId], []),
  'addExpense' : IDL.Func([Expense], [], []),
  'addGSTRate' : IDL.Func([GSTRate], [], []),
  'addPayment' : IDL.Func([Payment], [PaymentId], []),
  'addProduct' : IDL.Func([Product], [ProductId], []),
  'addProductCategory' : IDL.Func([IDL.Text], [], []),
  'addSale' : IDL.Func([Sale], [SaleId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'deleteGSTRate' : IDL.Func([IDL.Text], [], []),
  'deleteProductCategory' : IDL.Func([IDL.Text], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllGSTRates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, GSTRate))],
      ['query'],
    ),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllProductCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ProductCategory))],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
  'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getReports' : IDL.Func([], [Reports], ['query']),
  'getSale' : IDL.Func([SaleId], [IDL.Opt(Sale)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFirstUser' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCustomer' : IDL.Func([CustomerId, Customer], [], []),
  'updateExpense' : IDL.Func([ExpenseId, Expense], [], []),
  'updatePayment' : IDL.Func([PaymentId, Payment], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'updateSale' : IDL.Func([SaleId, Sale], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerId = IDL.Nat;
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'outstandingDue' : IDL.Nat,
    'totalPurchases' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ExpenseId = IDL.Nat;
  const ExpenseCategory = IDL.Variant({
    'other' : IDL.Null,
    'labour' : IDL.Null,
    'rent' : IDL.Null,
    'transport' : IDL.Null,
    'electricity' : IDL.Null,
  });
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'date' : Time,
    'description' : IDL.Text,
    'recordedBy' : IDL.Principal,
    'category' : ExpenseCategory,
    'amount' : IDL.Nat,
  });
  const GSTRate = IDL.Record({ 'name' : IDL.Text, 'percentage' : IDL.Nat });
  const PaymentId = IDL.Nat;
  const SaleId = IDL.Nat;
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'bank' : IDL.Null,
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : PaymentId,
    'saleId' : SaleId,
    'date' : Time,
    'mode' : PaymentMode,
    'notes' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const ProductCategory = IDL.Variant({
    'other' : IDL.Null,
    'tile' : IDL.Null,
    'granite' : IDL.Null,
    'marble' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'minStockAlert' : IDL.Nat,
    'category' : ProductCategory,
    'currentStock' : IDL.Nat,
    'basePrice' : IDL.Nat,
    'qrCode' : IDL.Text,
  });
  const SaleStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const SaleItem = IDL.Record({
    'productId' : ProductId,
    'gstAmount' : IDL.Nat,
    'quantity' : IDL.Nat,
    'gstRate' : GSTRate,
    'unitPrice' : IDL.Nat,
  });
  const Sale = IDL.Record({
    'id' : SaleId,
    'paymentStatus' : SaleStatus,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'totalGST' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'invoiceNumber' : IDL.Text,
    'transportCharge' : IDL.Nat,
    'discount' : IDL.Nat,
    'customerId' : CustomerId,
    'items' : IDL.Vec(SaleItem),
    'subtotal' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Reports = IDL.Record({
    'lowStockReport' : IDL.Vec(Product),
    'expenses' : IDL.Vec(Expense),
    'totalSales' : IDL.Nat,
    'topSellingProducts' : IDL.Vec(Product),
    'totalRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func([Customer], [CustomerId], []),
    'addExpense' : IDL.Func([Expense], [], []),
    'addGSTRate' : IDL.Func([GSTRate], [], []),
    'addPayment' : IDL.Func([Payment], [PaymentId], []),
    'addProduct' : IDL.Func([Product], [ProductId], []),
    'addProductCategory' : IDL.Func([IDL.Text], [], []),
    'addSale' : IDL.Func([Sale], [SaleId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'deleteGSTRate' : IDL.Func([IDL.Text], [], []),
    'deleteProductCategory' : IDL.Func([IDL.Text], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllGSTRates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, GSTRate))],
        ['query'],
      ),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllProductCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ProductCategory))],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllSales' : IDL.Func([], [IDL.Vec(Sale)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
    'getPayment' : IDL.Func([PaymentId], [IDL.Opt(Payment)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getReports' : IDL.Func([], [Reports], ['query']),
    'getSale' : IDL.Func([SaleId], [IDL.Opt(Sale)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFirstUser' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCustomer' : IDL.Func([CustomerId, Customer], [], []),
    'updateExpense' : IDL.Func([ExpenseId, Expense], [], []),
    'updatePayment' : IDL.Func([PaymentId, Payment], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'updateSale' : IDL.Func([SaleId, Sale], [], []),
  });
};

export const init = ({ IDL }) => { return []; };