/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanySettings {
  'branch' : string,
  'ifscCode' : string,
  'city' : string,
  'name' : string,
  'bankName' : string,
  'gstin' : string,
  'address' : string,
  'accountNumber' : string,
  'phone' : string,
}
export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'outstandingDue' : bigint,
  'totalPurchases' : bigint,
  'address' : string,
  'phone' : string,
}
export type CustomerId = bigint;
export interface Expense {
  'id' : ExpenseId,
  'date' : Time,
  'description' : string,
  'recordedBy' : Principal,
  'category' : ExpenseCategory,
  'amount' : bigint,
}
export type ExpenseCategory = { 'other' : null } |
  { 'labour' : null } |
  { 'rent' : null } |
  { 'transport' : null } |
  { 'electricity' : null };
export type ExpenseId = bigint;
export interface GSTRate { 'name' : string, 'percentage' : bigint }
export interface Payment {
  'id' : PaymentId,
  'saleId' : SaleId,
  'date' : Time,
  'mode' : PaymentMode,
  'notes' : string,
  'amount' : bigint,
}
export type PaymentId = bigint;
export type PaymentMode = { 'upi' : null } |
  { 'bank' : null } |
  { 'cash' : null } |
  { 'cheque' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Time,
  'minStockAlert' : bigint,
  'category' : ProductCategory,
  'currentStock' : bigint,
  'basePrice' : bigint,
  'qrCode' : string,
}
export type ProductCategory = { 'other' : null } |
  { 'tile' : null } |
  { 'granite' : null } |
  { 'marble' : null };
export type ProductId = bigint;
export interface Reports {
  'lowStockReport' : Array<Product>,
  'expenses' : Array<Expense>,
  'totalSales' : bigint,
  'topSellingProducts' : Array<Product>,
  'totalRevenue' : bigint,
}
export interface Sale {
  'id' : SaleId,
  'paymentStatus' : SaleStatus,
  'createdAt' : Time,
  'createdBy' : Principal,
  'totalGST' : bigint,
  'grandTotal' : bigint,
  'invoiceNumber' : string,
  'transportCharge' : bigint,
  'discount' : bigint,
  'customerId' : CustomerId,
  'items' : Array<SaleItem>,
  'subtotal' : bigint,
}
export type SaleId = bigint;
export interface SaleItem {
  'productId' : ProductId,
  'gstAmount' : bigint,
  'quantity' : bigint,
  'gstRate' : GSTRate,
  'unitPrice' : bigint,
}
export type SaleStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomer' : ActorMethod<[Customer], CustomerId>,
  'addExpense' : ActorMethod<[Expense], undefined>,
  'addGSTRate' : ActorMethod<[GSTRate], undefined>,
  'addPayment' : ActorMethod<[Payment], PaymentId>,
  'addProduct' : ActorMethod<[Product], ProductId>,
  'addProductCategory' : ActorMethod<[string], undefined>,
  'addSale' : ActorMethod<[Sale], SaleId>,
  'deleteCustomer' : ActorMethod<[CustomerId], undefined>,
  'deleteExpense' : ActorMethod<[ExpenseId], undefined>,
  'deleteGSTRate' : ActorMethod<[string], undefined>,
  'deletePayment' : ActorMethod<[PaymentId], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteProductCategory' : ActorMethod<[string], undefined>,
  'deleteSale' : ActorMethod<[SaleId], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllGSTRates' : ActorMethod<[], Array<[string, GSTRate]>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProductCategories' : ActorMethod<[], Array<[string, ProductCategory]>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSales' : ActorMethod<[], Array<Sale>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCompanySettings' : ActorMethod<[], CompanySettings>,
  'getCustomer' : ActorMethod<[CustomerId], Customer>,
  'getPayment' : ActorMethod<[PaymentId], [] | [Payment]>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getReports' : ActorMethod<[], Reports>,
  'getSale' : ActorMethod<[SaleId], [] | [Sale]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserPassword' : ActorMethod<[], boolean>,
  'isFirstUser' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCompanySettings' : ActorMethod<[CompanySettings], undefined>,
  'setUserPassword' : ActorMethod<[string], undefined>,
  'updateCustomer' : ActorMethod<[CustomerId, Customer], undefined>,
  'updateExpense' : ActorMethod<[ExpenseId, Expense], undefined>,
  'updatePayment' : ActorMethod<[PaymentId, Payment], undefined>,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
  'updateSale' : ActorMethod<[SaleId, Sale], undefined>,
  'verifyUserPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];