/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface SaleItem {
    productId: ProductId;
    gstAmount: bigint;
    quantity: bigint;
    gstRate: GSTRate;
    unitPrice: bigint;
}
export interface GSTRate {
    name: string;
    percentage: bigint;
}
export type Time = bigint;
export interface Payment {
    id: PaymentId;
    saleId: SaleId;
    date: Time;
    mode: PaymentMode;
    notes: string;
    amount: bigint;
}
export interface Sale {
    id: SaleId;
    paymentStatus: SaleStatus;
    createdAt: Time;
    createdBy: Principal;
    totalGST: bigint;
    grandTotal: bigint;
    invoiceNumber: string;
    transportCharge: bigint;
    discount: bigint;
    customerId: CustomerId;
    items: Array<SaleItem>;
    subtotal: bigint;
}
export interface Expense {
    id: ExpenseId;
    date: Time;
    description: string;
    recordedBy: Principal;
    category: ExpenseCategory;
    amount: bigint;
}
export interface Customer {
    id: CustomerId;
    name: string;
    createdAt: Time;
    email: string;
    outstandingDue: bigint;
    totalPurchases: bigint;
    address: string;
    phone: string;
}
export type PaymentId = bigint;
export type CustomerId = bigint;
export type ExpenseId = bigint;
export type SaleId = bigint;
export type ProductId = bigint;
export interface Product {
    id: ProductId;
    name: string;
    createdAt: Time;
    minStockAlert: bigint;
    category: ProductCategory;
    currentStock: bigint;
    basePrice: bigint;
    qrCode: string;
}
export interface Reports {
    lowStockReport: Array<Product>;
    expenses: Array<Expense>;
    totalSales: bigint;
    topSellingProducts: Array<Product>;
    totalRevenue: bigint;
}
export enum ExpenseCategory {
    other = "other",
    labour = "labour",
    rent = "rent",
    transport = "transport",
    electricity = "electricity"
}
export enum PaymentMode {
    upi = "upi",
    bank = "bank",
    cash = "cash",
    cheque = "cheque"
}
export enum ProductCategory {
    other = "other",
    tile = "tile",
    granite = "granite",
    marble = "marble"
}
export enum SaleStatus {
    paid = "paid",
    unpaid = "unpaid",
    partial = "partial"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCustomer(customer: Customer): Promise<CustomerId>;
    addExpense(expense: Expense): Promise<void>;
    addGSTRate(rate: GSTRate): Promise<void>;
    addPayment(payment: Payment): Promise<PaymentId>;
    addProduct(product: Product): Promise<ProductId>;
    addProductCategory(category: string): Promise<void>;
    addSale(sale: Sale): Promise<SaleId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteExpense(id: ExpenseId): Promise<void>;
    deleteGSTRate(name: string): Promise<void>;
    deleteProductCategory(category: string): Promise<void>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllGSTRates(): Promise<Array<[string, GSTRate]>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllProductCategories(): Promise<Array<[string, ProductCategory]>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllSales(): Promise<Array<Sale>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: CustomerId): Promise<Customer>;
    getPayment(id: PaymentId): Promise<Payment | null>;
    getProduct(name: string): Promise<Product | null>;
    getReports(): Promise<Reports>;
    getSale(id: SaleId): Promise<Sale | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCustomer(customerId: CustomerId, customer: Customer): Promise<void>;
    updateExpense(id: ExpenseId, expense: Expense): Promise<void>;
    updatePayment(paymentId: PaymentId, payment: Payment): Promise<void>;
    updateProduct(name: string, product: Product): Promise<void>;
    updateSale(id: SaleId, sale: Sale): Promise<void>;
}
import type { CustomerId as _CustomerId, Expense as _Expense, ExpenseCategory as _ExpenseCategory, ExpenseId as _ExpenseId, Payment as _Payment, PaymentId as _PaymentId, PaymentMode as _PaymentMode, Product as _Product, ProductCategory as _ProductCategory, ProductId as _ProductId, Reports as _Reports, Sale as _Sale, SaleId as _SaleId, SaleItem as _SaleItem, SaleStatus as _SaleStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCustomer(arg0: Customer): Promise<CustomerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addGSTRate(arg0: GSTRate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGSTRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGSTRate(arg0);
            return result;
        }
    }
    async addPayment(arg0: Payment): Promise<PaymentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(to_candid_Payment_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(to_candid_Payment_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_Product_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_Product_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addProductCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductCategory(arg0);
            return result;
        }
    }
    async addSale(arg0: Sale): Promise<SaleId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(to_candid_Sale_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(to_candid_Sale_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteExpense(arg0: ExpenseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteGSTRate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGSTRate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGSTRate(arg0);
            return result;
        }
    }
    async deleteProductCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductCategory(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGSTRates(): Promise<Array<[string, GSTRate]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGSTRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGSTRates();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductCategories(): Promise<Array<[string, ProductCategory]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductCategories();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductCategories();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSales(): Promise<Array<Sale>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSales();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSales();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getPayment(arg0: PaymentId): Promise<Payment | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayment(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayment(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReports(): Promise<Reports> {
        if (this.processError) {
            try {
                const result = await this.actor.getReports();
                return from_candid_Reports_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReports();
            return from_candid_Reports_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSale(arg0: SaleId): Promise<Sale | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSale(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSale(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return result;
        }
    }
    async updateExpense(arg0: ExpenseId, arg1: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePayment(arg0: PaymentId, arg1: Payment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, to_candid_Payment_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, to_candid_Payment_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: string, arg1: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_Product_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_Product_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSale(arg0: SaleId, arg1: Sale): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSale(arg0, to_candid_Sale_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSale(arg0, to_candid_Sale_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ExpenseCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Reports_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reports): Reports {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_SaleStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaleStatus): SaleStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Sale_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sale): Sale {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Payment]): Payment | null {
    return value.length === 0 ? null : from_candid_Payment_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sale]): Sale | null {
    return value.length === 0 ? null : from_candid_Sale_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExpenseId;
    date: _Time;
    description: string;
    recordedBy: Principal;
    category: _ExpenseCategory;
    amount: bigint;
}): {
    id: ExpenseId;
    date: Time;
    description: string;
    recordedBy: Principal;
    category: ExpenseCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        recordedBy: value.recordedBy,
        category: from_candid_ExpenseCategory_n22(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentId;
    saleId: _SaleId;
    date: _Time;
    mode: _PaymentMode;
    notes: string;
    amount: bigint;
}): {
    id: PaymentId;
    saleId: SaleId;
    date: Time;
    mode: PaymentMode;
    notes: string;
    amount: bigint;
} {
    return {
        id: value.id,
        saleId: value.saleId,
        date: value.date,
        mode: from_candid_PaymentMode_n27(_uploadFile, _downloadFile, value.mode),
        notes: value.notes,
        amount: value.amount
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    createdAt: _Time;
    minStockAlert: bigint;
    category: _ProductCategory;
    currentStock: bigint;
    basePrice: bigint;
    qrCode: string;
}): {
    id: ProductId;
    name: string;
    createdAt: Time;
    minStockAlert: bigint;
    category: ProductCategory;
    currentStock: bigint;
    basePrice: bigint;
    qrCode: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        minStockAlert: value.minStockAlert,
        category: from_candid_ProductCategory_n31(_uploadFile, _downloadFile, value.category),
        currentStock: value.currentStock,
        basePrice: value.basePrice,
        qrCode: value.qrCode
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SaleId;
    paymentStatus: _SaleStatus;
    createdAt: _Time;
    createdBy: Principal;
    totalGST: bigint;
    grandTotal: bigint;
    invoiceNumber: string;
    transportCharge: bigint;
    discount: bigint;
    customerId: _CustomerId;
    items: Array<_SaleItem>;
    subtotal: bigint;
}): {
    id: SaleId;
    paymentStatus: SaleStatus;
    createdAt: Time;
    createdBy: Principal;
    totalGST: bigint;
    grandTotal: bigint;
    invoiceNumber: string;
    transportCharge: bigint;
    discount: bigint;
    customerId: CustomerId;
    items: Array<SaleItem>;
    subtotal: bigint;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_SaleStatus_n39(_uploadFile, _downloadFile, value.paymentStatus),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        totalGST: value.totalGST,
        grandTotal: value.grandTotal,
        invoiceNumber: value.invoiceNumber,
        transportCharge: value.transportCharge,
        discount: value.discount,
        customerId: value.customerId,
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowStockReport: Array<_Product>;
    expenses: Array<_Expense>;
    totalSales: bigint;
    topSellingProducts: Array<_Product>;
    totalRevenue: bigint;
}): {
    lowStockReport: Array<Product>;
    expenses: Array<Expense>;
    totalSales: bigint;
    topSellingProducts: Array<Product>;
    totalRevenue: bigint;
} {
    return {
        lowStockReport: from_candid_vec_n33(_uploadFile, _downloadFile, value.lowStockReport),
        expenses: from_candid_vec_n19(_uploadFile, _downloadFile, value.expenses),
        totalSales: value.totalSales,
        topSellingProducts: from_candid_vec_n33(_uploadFile, _downloadFile, value.topSellingProducts),
        totalRevenue: value.totalRevenue
    };
}
function from_candid_tuple_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _ProductCategory]): [string, ProductCategory] {
    return [
        value[0],
        from_candid_ProductCategory_n31(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    labour: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    electricity: null;
}): ExpenseCategory {
    return "other" in value ? ExpenseCategory.other : "labour" in value ? ExpenseCategory.labour : "rent" in value ? ExpenseCategory.rent : "transport" in value ? ExpenseCategory.transport : "electricity" in value ? ExpenseCategory.electricity : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    bank: null;
} | {
    cash: null;
} | {
    cheque: null;
}): PaymentMode {
    return "upi" in value ? PaymentMode.upi : "bank" in value ? PaymentMode.bank : "cash" in value ? PaymentMode.cash : "cheque" in value ? PaymentMode.cheque : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    tile: null;
} | {
    granite: null;
} | {
    marble: null;
}): ProductCategory {
    return "other" in value ? ProductCategory.other : "tile" in value ? ProductCategory.tile : "granite" in value ? ProductCategory.granite : "marble" in value ? ProductCategory.marble : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
}): SaleStatus {
    return "paid" in value ? SaleStatus.paid : "unpaid" in value ? SaleStatus.unpaid : "partial" in value ? SaleStatus.partial : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _ProductCategory]>): Array<[string, ProductCategory]> {
    return value.map((x)=>from_candid_tuple_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Sale>): Array<Sale> {
    return value.map((x)=>from_candid_Sale_n37(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenseCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Expense_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Payment_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Payment): _Payment {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Product_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): _Product {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_SaleStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaleStatus): _SaleStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Sale_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sale): _Sale {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    name: string;
    createdAt: Time;
    minStockAlert: bigint;
    category: ProductCategory;
    currentStock: bigint;
    basePrice: bigint;
    qrCode: string;
}): {
    id: _ProductId;
    name: string;
    createdAt: _Time;
    minStockAlert: bigint;
    category: _ProductCategory;
    currentStock: bigint;
    basePrice: bigint;
    qrCode: string;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        minStockAlert: value.minStockAlert,
        category: to_candid_ProductCategory_n11(_uploadFile, _downloadFile, value.category),
        currentStock: value.currentStock,
        basePrice: value.basePrice,
        qrCode: value.qrCode
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: SaleId;
    paymentStatus: SaleStatus;
    createdAt: Time;
    createdBy: Principal;
    totalGST: bigint;
    grandTotal: bigint;
    invoiceNumber: string;
    transportCharge: bigint;
    discount: bigint;
    customerId: CustomerId;
    items: Array<SaleItem>;
    subtotal: bigint;
}): {
    id: _SaleId;
    paymentStatus: _SaleStatus;
    createdAt: _Time;
    createdBy: Principal;
    totalGST: bigint;
    grandTotal: bigint;
    invoiceNumber: string;
    transportCharge: bigint;
    discount: bigint;
    customerId: _CustomerId;
    items: Array<_SaleItem>;
    subtotal: bigint;
} {
    return {
        id: value.id,
        paymentStatus: to_candid_SaleStatus_n15(_uploadFile, _downloadFile, value.paymentStatus),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        totalGST: value.totalGST,
        grandTotal: value.grandTotal,
        invoiceNumber: value.invoiceNumber,
        transportCharge: value.transportCharge,
        discount: value.discount,
        customerId: value.customerId,
        items: value.items,
        subtotal: value.subtotal
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ExpenseId;
    date: Time;
    description: string;
    recordedBy: Principal;
    category: ExpenseCategory;
    amount: bigint;
}): {
    id: _ExpenseId;
    date: _Time;
    description: string;
    recordedBy: Principal;
    category: _ExpenseCategory;
    amount: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        recordedBy: value.recordedBy,
        category: to_candid_ExpenseCategory_n3(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: PaymentId;
    saleId: SaleId;
    date: Time;
    mode: PaymentMode;
    notes: string;
    amount: bigint;
}): {
    id: _PaymentId;
    saleId: _SaleId;
    date: _Time;
    mode: _PaymentMode;
    notes: string;
    amount: bigint;
} {
    return {
        id: value.id,
        saleId: value.saleId,
        date: value.date,
        mode: to_candid_PaymentMode_n7(_uploadFile, _downloadFile, value.mode),
        notes: value.notes,
        amount: value.amount
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    other: null;
} | {
    tile: null;
} | {
    granite: null;
} | {
    marble: null;
} {
    return value == ProductCategory.other ? {
        other: null
    } : value == ProductCategory.tile ? {
        tile: null
    } : value == ProductCategory.granite ? {
        granite: null
    } : value == ProductCategory.marble ? {
        marble: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaleStatus): {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
} {
    return value == SaleStatus.paid ? {
        paid: null
    } : value == SaleStatus.unpaid ? {
        unpaid: null
    } : value == SaleStatus.partial ? {
        partial: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    other: null;
} | {
    labour: null;
} | {
    rent: null;
} | {
    transport: null;
} | {
    electricity: null;
} {
    return value == ExpenseCategory.other ? {
        other: null
    } : value == ExpenseCategory.labour ? {
        labour: null
    } : value == ExpenseCategory.rent ? {
        rent: null
    } : value == ExpenseCategory.transport ? {
        transport: null
    } : value == ExpenseCategory.electricity ? {
        electricity: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    upi: null;
} | {
    bank: null;
} | {
    cash: null;
} | {
    cheque: null;
} {
    return value == PaymentMode.upi ? {
        upi: null
    } : value == PaymentMode.bank ? {
        bank: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value == PaymentMode.cheque ? {
        cheque: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
